import json
import os
import sys
import joblib
import numpy as np
from datetime import datetime
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from db_config import get_connection, adapt_sql

app = FastAPI(title="SA Algal Bloom Monitor API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Load ML model once at startup ──
MODEL = None
ENCODER = None

def load_model():
    global MODEL, ENCODER
    try:
        MODEL   = joblib.load("ml_engine/bloom_model.pkl")
        ENCODER = joblib.load("ml_engine/label_encoder.pkl")
        print("ML model loaded OK")
    except Exception as e:
        print(f"Model load warning: {e}")

load_model()

# ════════════════════════════════════
# ENDPOINT 1 — Health check
# ════════════════════════════════════
@app.get("/api/health")
def health():
    return {
        "status":    "ok",
        "timestamp": datetime.now().isoformat(),
        "model":     "loaded" if MODEL else "not loaded"
    }

# ════════════════════════════════════
# ENDPOINT 2 — Bloom heatmap
# Reads committed GeoJSON file (generated by coastal_bloom_map.py)
# ════════════════════════════════════
@app.get("/api/bloom-heatmap")
def bloom_heatmap():
    path = "data/indices/bloom_heatmap_latest.geojson"
    if os.path.exists(path):
        try:
            with open(path) as f:
                return json.load(f)
        except Exception:
            pass
    return {"type": "FeatureCollection", "features": []}

# ════════════════════════════════════
# ENDPOINT 3 — Cell counts
# Queries KareniaReadings from Supabase
# ════════════════════════════════════
@app.get("/api/cell-counts")
def cell_counts():
    try:
        conn   = get_connection()
        cursor = conn.cursor()
        cursor.execute(adapt_sql("""
            SELECT TOP 100
                beach_name,
                latitude,
                longitude,
                cell_count_per_litre,
                severity,
                recorded_at
            FROM KareniaReadings
            ORDER BY recorded_at DESC
        """))
        rows = cursor.fetchall()
        conn.close()
        return [
            {
                "beach_name":           r[0],
                "latitude":             r[1],
                "longitude":            r[2],
                "cell_count_per_litre": r[3],
                "severity":             r[4],
                "recorded_at":          r[5].isoformat() if r[5] else None
            }
            for r in rows
        ]
    except Exception as e:
        return []   # return empty list, never an error object

# ════════════════════════════════════
# ENDPOINT 4 — Weather
# Queries WeatherReadings from Supabase.
# Fetches the 1000 most recent rows then deduplicates in Python
# so one row per location is returned. This avoids correlated
# subquery issues across SQL Server / PostgreSQL.
# ════════════════════════════════════
@app.get("/api/weather")
def weather():
    try:
        conn   = get_connection()
        cursor = conn.cursor()
        cursor.execute(adapt_sql("""
            SELECT TOP 1000
                location_name,
                latitude,
                longitude,
                wind_speed,
                wind_direction,
                sea_surface_temp,
                solar_radiation,
                wave_height,
                recorded_at
            FROM WeatherReadings
            ORDER BY recorded_at DESC
        """))
        rows = cursor.fetchall()
        conn.close()

        # Keep only the most recent row per location (first occurrence after ORDER BY DESC)
        seen   = set()
        result = []
        for r in rows:
            loc = r[0]
            if loc not in seen:
                seen.add(loc)
                result.append({
                    "location_name":    r[0],
                    "latitude":         r[1],
                    "longitude":        r[2],
                    "wind_speed":       r[3],
                    "wind_direction":   r[4],
                    "sea_surface_temp": r[5],
                    "solar_radiation":  r[6],
                    "wave_height":      r[7],
                    "recorded_at":      r[8].isoformat() if r[8] else None
                })
        return result
    except Exception as e:
        return []   # return empty list, never an error object

# ════════════════════════════════════
# ENDPOINT 5 — 72hr forecast
# ════════════════════════════════════
@app.get("/api/forecast/72hr")
def forecast_72hr():
    path = "data/forecasts/forecast_latest.json"
    if os.path.exists(path):
        try:
            with open(path) as f:
                data = json.load(f)
            return {
                "generated_at": data.get("generated_at"),
                "snapshots":    data.get("snapshots", {}),
                "alerts":       data.get("alerts", [])
            }
        except Exception:
            pass
    return {"generated_at": None, "snapshots": {}, "alerts": []}

# ════════════════════════════════════
# ENDPOINT 6 — Alerts
# ════════════════════════════════════
@app.get("/api/alerts")
def alerts():
    path = "data/forecasts/forecast_latest.json"
    active = []
    if os.path.exists(path):
        try:
            with open(path) as f:
                data = json.load(f)
            for a in data.get("alerts", []):
                active.append({
                    "zone_name":      a["zone"],
                    "predicted_hour": a["hour"],
                    "particles":      a["particles"],
                    "severity":       "High",
                    "generated_at":   data.get("generated_at")
                })
        except Exception:
            pass
    return {
        "total_alerts": len(active),
        "checked_at":   datetime.now().isoformat(),
        "alerts":       active
    }

# ════════════════════════════════════
# ENDPOINT 7 — Beach safety scores
# Primary: query KareniaReadings from Supabase and compute scores.
# Fallback: read data/beach_safety_scores.json if DB is unavailable.
# ════════════════════════════════════

def _cell_count_to_score(cell_count):
    """Simplified SA Health threshold scoring (no wind/satellite needed)."""
    if cell_count >= 50000:
        return 20.0, "Danger",   "#d32f2f"
    elif cell_count >= 10000:
        return 42.0, "Warning",  "#f57c00"
    elif cell_count >= 1000:
        return 65.0, "Caution",  "#fbc02d"
    else:
        return 85.0, "Safe",     "#388e3c"

@app.get("/api/beach-safety")
def beach_safety():
    # ── Primary: compute live from Supabase KareniaReadings ──
    try:
        conn   = get_connection()
        cursor = conn.cursor()
        cursor.execute(adapt_sql("""
            SELECT TOP 20
                beach_name,
                latitude,
                longitude,
                cell_count_per_litre,
                severity
            FROM KareniaReadings
            ORDER BY cell_count_per_litre DESC
        """))
        rows = cursor.fetchall()
        conn.close()

        if rows:
            scores = []
            for r in rows:
                cell_count = r[3] or 0
                score, label, color = _cell_count_to_score(cell_count)
                scores.append({
                    "beach":      r[0],
                    "lat":        r[1],
                    "lon":        r[2],
                    "score":      score,
                    "label":      label,
                    "color":      color,
                    "cell_count": cell_count,
                    "wind_speed": 0,
                    "wind_dir":   0,
                    "sfabi":      0,
                    "data_source": "KareniaReadings"
                })
            return {"generated_at": datetime.now().isoformat(), "scores": scores}
    except Exception:
        pass

    # ── Fallback: read committed JSON file ──
    path = "data/beach_safety_scores.json"
    if os.path.exists(path):
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass

    return {"generated_at": datetime.now().isoformat(), "scores": []}

# ════════════════════════════════════
# ENDPOINT 8 — ML prediction
# ════════════════════════════════════
@app.get("/api/predict")
def predict(
    sfabi: float = 0.1,
    sst:   float = 22.0,
    wind:  float = 10.0
):
    if not MODEL:
        return {"error": "Model not loaded"}
    X          = np.array([[wind, 180, sst, 300, 0.5, sfabi, sfabi*0.8, -34.9, 138.6]])
    pred       = MODEL.predict(X)[0]
    proba      = MODEL.predict_proba(X)[0]
    confidence = round(float(proba.max()) * 100, 1)
    severity   = ENCODER.inverse_transform([pred])[0]
    return {
        "severity":   severity,
        "confidence": confidence,
        "sfabi":      sfabi,
        "sst":        sst,
        "wind":       wind
    }
